Polar Plotter Project: Master Class Reference
Master Class Reference
#include <Master.h>
Classes
union packet1
encoder_data allows easy partitioning of encoder data
Public Member Functions
Master (base_text_serial *)
void CLEAR (uint8_t)
void Initiate (uint8_t)
bool Get_Checksum_flag (void)
uint8_t Get_Checksum_Error (void)
int32_t Get_Encoder (void)
Protected Attributes
base_text_serial * ptr_to_serial
The encoder driver class needs a pointer to the serial port used to output to the terminal.
bool error_flag
flag indicating transfer error on encoder 1
int32_t encoder
encoder value received from Slave_Driver
uint8_t Checksum_Error
encoder transfer error 1
uint8_t Check_Sum_Master
check sum computed here in master for encoder 1
uint8_t Slave_Sum
check sum computed in slave for encoder 1
uint8_t dummy
counter used to delay so SPI works
uint8_t encoder_num
integer to tell Master which encoder reading to get from Slave_Driver
union Master::packet1 encoder_data
Detailed Description
Master.cpp is a class with methods for orchestrating and controlling the flow of data transfers on the SPI bus between a master device and a slave device. The data being transfered are new encoder positions from the two motors so that the task_PID class can keep track of where the motors are. The encoder values used in the PID calculations are stored in the main program and are updated in Master via pointers so that other objects can use them as well.
Definition at line 31 of file Master.h.
Constructor & Destructor Documentation
Master::Master (base_text_serial * p_serial_port)
The constructor takes in a serial pointer and saves it locally and constructs a Master object. The object sets up SPI communications as a master.
Parameters
p_serial_port serial object to allow printing
Definition at line 25 of file Master.cpp.
References CLEAR(), and ptr_to_serial.
Member Function Documentation
void Master::CLEAR (uint8_t motor_num)
Clear is a method to clear a pair of counters located on another chip. Associated values in this class are also cleared
Parameters
motor_num pass in the value of which motor's encoder you would like to reset. motor_num=1 corresponds to command 3 and motor_num=2 sends command 4.
Definition at line 53 of file Master.cpp.
References Checksum_Error, dummy, encoder, and ptr_to_serial.
Referenced by Master(), and Go_Home::run().
uint8_t Master::Get_Checksum_Error (void)
Get_Checksum_Error gets the number of encoder transfer errors experienced
Definition at line 188 of file Master.cpp.
References Checksum_Error.
bool Master::Get_Checksum_flag (void)
Get_Checksum_flag is a method which returns true if the specified channel has experienced SPI transfer error and false if the channel's transfer went well.
Definition at line 196 of file Master.cpp.
References error_flag.
int32_t Master::Get_Encoder (void)
Get_Encoder gets an encoder reading
Definition at line 181 of file Master.cpp.
References encoder.
void Master::Initiate (uint8_t encoder_select)
Initiate communicates with another SPI device. Each encoder value is 32 bits or 4 bytes. The data transfer across the SPI bus happens one byte at a time. Each byte is stored in the union encoder_data. After the complete encoder value has been recieved, one more data transfer occurs to get the checksum from the slave device. The checksum for the received data is calculated and then compared to the checksum sent by the slave. If the checksums don't match, there has been a transfer error and the pointer to the encoder variable in PID_test is not updated. If the checksums match, then the pointer to the encoder variable gets updated with the new encoder position.
Parameters
encoder_select Initiate must be fed which channel (motor) you desire encoder ticks from
Definition at line 110 of file Master.cpp.
References Check_Sum_Master, Checksum_Error, dummy, encoder, encoder_num, error_flag, Master::packet1::parts, Slave_Sum, and Master::packet1::whole.
The documentation for this class was generated from the following files:
Master.h
Master.cpp