Polar Plotter Project: sd_card Class Reference
sd_card Class Reference
#include <sd_card.h>
Public Member Functions
sd_card (void)
bool ready_to_send (void)
bool putchar (char)
void puts (char const *)
void transmit_now (void)
FRESULT mount (unsigned char)
bool open_directory (const char *)
FRESULT open_file_readonly (const char *)
FRESULT open_file_overwrite (const char *)
FRESULT open_file_append (const char *)
FRESULT close_file (void)
uint16_t open_new_data_file (char const *, char const *)
Public Member Functions inherited from base_text_serial
base_text_serial (void)
virtual bool check_for_char (void)
virtual char getchar (void)
virtual void clear_screen (void)
base_text_serial & operator<< (bool)
base_text_serial & operator<< (const char *)
base_text_serial & operator<< (unsigned char)
base_text_serial & operator<< (char num)
base_text_serial & operator<< (unsigned int)
base_text_serial & operator<< (int)
base_text_serial & operator<< (unsigned long)
base_text_serial & operator<< (long)
base_text_serial & operator<< (unsigned long long)
base_text_serial & operator<< (ser_manipulator)
Protected Attributes
uint8_t sector_buffer [SD_BLOCK_SIZE]
This buffer holds data which is to be saved into a block on the SD card.
queue< char, SD_L_BUF_IDX_T,
SD_LINE_BUF_SIZE > line_buffer
This buffer holds one line of text to be written to the card.
uint8_t * p_line_buffer
Points to buffer for lines of text.
int index
Index into buffer at which to put data.
unsigned long write_addr
Address to which data is being written.
FATFS the_fat_fs
This is a filesystem data structure (see ff.h).
FRESULT dir_file_result
This item holds a result code from opening a directory and/or a file.
DIR the_dir
This is a directory data structure (see ff.h).
FIL the_file
This data structure stores information about a file on the disk.
Protected Attributes inherited from base_text_serial
unsigned char base
This is the currently used base for converting numbers to text.
bool print_ascii
bool pgm_string
char precision
Detailed Description
This class implements an interface to an SD card. Data is stored up in a buffer, then written to the card when the buffer becomes full or when the send_now modifier is inserted into the SD card object's output stream. (Alternatively, one can specify that carriage returns cause writing to the card using the macro SD_SEND_NOW_CHAR in sd_card.h.) The SPI interface to the SD card is used, as it is much simpler and requires less wires than the full high-speed interface. The SPI interface is a bit slow, though.
The ELM-FAT-FS library is used for its low-level and FAT file system drivers. This library can be found at http://elm-chan.org/fsw/ff/00index_e.html. The filesystem library interfaces with the sd_card class through two sets of C functions. The first set of functions is in files ff.h and ff.c; these functions provide the functionality of a file system: initializing and mounting volumes, opening files and directories, reading and writing data, and so on. The second set of functions is a set of callback functions which are provided in sd_card.cc. Written in C, these callbacks are called by the ELM-FAT-FS library to provide platform and media specific access; they allow the AVR processor to work with the SD card. Most of the C functions in sd_card.cc are slightly modified versions of functions from the AVR-specific example files distributed with the ELM-FAT-FS library.
Preparing an SD Card for Use
The SD cards used by this program should be formatted as MS-DOS style volumes in the "floppy disk" style, not the "hard disk" style. This means that there should not be a partition table, with one or more partitions each having a filesystem. Instead, the disk's main volume should be formatted. Many SD cards come formatted in the wrong style when purchased; the following steps will help determine if a card is formatted in the right or wrong way:
Plug the card into a Linux computer.
Open the card in a file browser; ignore the contents and close the browser. Opening the card caused it to be automatically mounted, which is why it was worth doing.
Open a terminal window (konsole or gnome-terminal) and type 'mount'. Look near the end of the bunch of text which comes up for a line that looks like this:
/dev/sde1 on /media/disk type vfat (rw,nosuid,nodev,uhelper=hal,uid=1000,utf8,shortname=mixed,flush)
If the code /dev/xxxx on the left of the line ends with a number, such as /dev/sde1, you have the wrong kind of formatting; it will need to be reformatted. If the code has no number, such as /dev/sdf, then you should be able to use the card as is.
The device name is usually /dev/sdxx, but on some computers the name may be different, such as /dev/mmcblk0. In this case, partitions may be named like /dev/mmcblk0p1, and the device name is actually /dev/mmcblk0 including the "0" at the end.
Unmount the card. In KDE, use the device mounter's "eject" button; in Gnome right-click on the device icon and choose unmount.
The following process will format an SD card in "floppy disk style" on Linux:
Get to a Linux computer on which you have root (sudo) access. You need root access in order to write directly to the SD card.
Plug the card into an SD/MMC slot in the computer. Do not open it up in a file manager or mount it.
Repeat the steps for checking the card's formatting if necessary to find the device name /dev/xxxn for the card. Note that in /dev/xxxn, the "\c xxx" is letters (for example sdf) and the "\t n" is a number, almost always 1.
WARNING: You need to be very careful in the following command: Do not enter the designation of one of your computer's hard drives, as this command would then reformat your system drive and effectively wipe out all the data on that drive.
Run the following command:
sudo mkfs -t msdos -I /dev/xxx
Note that the number is left off the device name. What you are doing is formatting the disk without any partitions; the numbers referred to partitions on the disk.
Remove the card and re-insert it in the computer. Make sure you can open it in a file manager as usual.
Unmount the card, remove it from the PC, and you're ready to use it to save some data.
Using the SD Card Driver Software
In order to use the SD card driver, one must have an AVR board with an SD card slot, and the board must be configured to operate with Vcc at 3.3 volts. It is possible that multiple SD cards could be used on the same board, but this has not been tested, and it would be rather weird to want to do so. Hot swapping the SD card is possible, but it's usually not a very good idea because of hardware considerations: SD cards have big internal power supply capacitance and tend to inflict brownouts on the AVR when plugged in. Also, making sure that all your reads and writes are finished before swapping the card can be a problem.
Configuration is done by modifying values in sd_card.h and ffconf.h. Recommended settings for ffconf.h (which configures the filesystem drivers) include the following:
_FS_TINY 0 unless you have >= 4K SRAM
_FS_READONLY 0 to enable writing
_FS_MINIMIZE 1 to save space
_USE_STRFUNC 0 unless you need strings
_USE_MKFS 0 unless you need to format
_USE_FORWARD 0 unless you need...this
_CODE_PAGE 1 for ASCII coding
_USE_LFN 0 to use short (8.3) filenames
Recommended settings for sd_card.h include the following:
SD_BLOCK_SIZE 512 This must be 512 for all SD cards
SD_LINE_BUF_SIZE 256 256 Anything from about 16 to 512 should work; this value can be adjusted to balance speed with memory usage.
The processs of reading or writing a file consists of the following steps:
Mount the card. This is Unix-talk for getting data from the boot record about where the partitions and base directories on the card can be found.
Open a file using a method such as open_file_readonly(), open_file_overwrite(), etc.
If lots of data is being logged, one can use the open_new_data_file() method which automatically creates file names in a sequence.
Use the overloaded shift operator "<<" to write data to the file, or use the more primitive methods getchar(), putchar(), and puts() to read and write characters from and to the file.
If at all possible, use the close_file() method to make sure all the data is saved to the file. If a file is not closed properly, some data may be left in the memory buffer and not written to the disk.
Functions tested and working
Opening an SD card formatted without a partition
Automatically creating data files in the root directory and writing to them
Bugs
When using SD cards formatted with one or more partitions, sometimes the files written by this driver aren't visible to a computer reading the card. Workaround: Make sure to use cards which don't have partitions on them.
Writing to the SD card can be very slow, and this code does not attempt to prevent blocking of the rest of the system during card writes.
Long file names have not been tested. They're probably not a good idea for a small embedded system anyway.
Internal stuff
The DSTATUS flag byte, given in sd_card.c, holds some status bits for the disk:
0x01: STA_NOINIT
0x02: STA_NODISK
0x04: STA_PROTECT
The FRESULT enumeration, given in ff.c, holds the result of a file operation. Its values are:
0: FR_OK
1: FR_DISK_ERR
2: FR_INT_ERR
3: FR_NOT_READY
4: FR_NO_FILE
5: FR_NO_PATH
6: FR_INVALID_NAME
7: FR_DENIED
8: FR_EXIST
9: FR_INVALID_OBJECT
10: FR_WRITE_PROTECTED
11: FR_INVALID_DRIVE
12: FR_NOT_ENABLED
13: FR_NO_FILESYSTEM
14: FR_MKFS_ABORTED
15: FR_TIMEOUT
Definition at line 325 of file sd_card.h.
Constructor & Destructor Documentation
sd_card::sd_card (void)
This constructor sets up an SD card interface. It calls the constructor of its base class base_text_serial and initializes the data buffer so that the buffer is ready to accept some data. It also configures the SPI port pins so that they are ready to communicate with the card. The constructor does not initialize the card; initialization is performed in the mount() method.
Definition at line 689 of file sd_card.cpp.
References dir_file_result, queue< qType, qIndexType, qSize >::get_p_buffer(), line_buffer, p_line_buffer, SD_CS_DDR, SD_CS_MASK, SD_CS_PORT, and STA_NOINIT.
Member Function Documentation
FRESULT sd_card::close_file (void)
This method closes a file. If there is any data left in the buffer, it is written to the card. Then further writing to this file is prevented unless the file is opened again.
Returns
The result code from calling f_close() to close the file
Definition at line 945 of file sd_card.cpp.
References dir_file_result, endl, GLOB_DEBUG, line_buffer, queue< qType, qIndexType, qSize >::num_items(), PMS, the_file, and transmit_now().
FRESULT sd_card::mount (unsigned char part_num)
This method performs an action equivalent to "mounting" the SD card (in POSIX talk). This means that the card interface is initialized, then the card's boot record and partition table and all that oddball stuff is scanned so that we will be able to find files on the card. Partition number 0 is always mounted.
Parameters
part_num The number of the partition to mount – ignored, we use 0 always
Returns
The result code from attempting to open the root directory; 0 means OK
Definition at line 805 of file sd_card.cpp.
References dir_file_result, disk_initialize(), the_dir, and the_fat_fs.
bool sd_card::open_directory (const char * path)
This method opens the given directory. The directory is identified by a path name which may go into several layers of subdirectories but must be less than 64 characters long. A valid path name might be "/data/strain.dat/recent"; note that forward slashes are used (POSIX style), not backslashes in the Windows style, and that 8.3 names are required.
Parameters
path A character string containing the full path name of the directory
Returns
True if the directory was opened OK, or false if it couldn't be opened
Definition at line 833 of file sd_card.cpp.
FRESULT sd_card::open_file_append (const char * path_name)
This method opens the given file for writing (the file can also be read). If the file doesn't yet exist, it is created; if it exists, it's opened in append mode.
WARNING, BUG, TODO: This method hasn't been finished yet and doesn't work.
Parameters
path_name The path name to the file, including the directory
Returns
The result code from the f_open() call attempting to open the file
Definition at line 912 of file sd_card.cpp.
References dir_file_result, endl, GLOB_DEBUG, PMS, and the_file.
FRESULT sd_card::open_file_overwrite (const char * path_name)
This method opens the given file for writing (the file can also be read). It leaves the read/write pointer at the beginning of the file so that old data will be overwritten.
Parameters
path_name The path name to the file, including the directory
Returns
The result code from the f_open() call attempting to open the file
Definition at line 878 of file sd_card.cpp.
References dir_file_result, endl, GLOB_DEBUG, PMS, and the_file.
Referenced by open_new_data_file().
FRESULT sd_card::open_file_readonly (const char * path_name)
This method opens the given file in read-only mode. The file must exist, and the volume in which the file exists must have already been mounted.
Parameters
path_name A path to the file to be opened
Returns
An FRESULT value (see ff.h) which tells if the file was opened successfully
Definition at line 846 of file sd_card.cpp.
References dir_file_result, endl, GLOB_DEBUG, PMS, and the_file.
uint16_t sd_card::open_new_data_file (char const * base_name, char const * extension)
This function opens a new data file, in the card's root directory, with a name which hasn't yet been used. Names are made by putting together a path, base name, number, and extension as in "/data/file_012.txt". The base name variable includes the path and the file name together, separated by forward slashes.
Parameters
base_name The base name, including path, such as "/data/log_" where the file name should be at most 5 characters long because 3 digits will be added. The base name should begin with a slash to be an absolute path name on a card.
extension The 3-character file name extension, such as "txt" or "csv"
Returns
The number used to make the new data file's name, or 0xFFFF for failure
Definition at line 979 of file sd_card.cpp.
References dir_file_result, endl, GLOB_DEBUG, open_file_overwrite(), PMS, and the_file.
bool sd_card::putchar (char to_put) virtual
This method puts one character into the buffer of data to be written to the card. If the buffer becomes full through this write, the buffer is automatically written to the card. This will take a long time, so it might be a good idea to control the times at which buffers full of data are written using the transmit_now() method to write data and chars_empty() to check how much space is left in the buffer. An error occurs if the buffer is full and there's no card to which to store data.
Parameters
to_put The character to be written into the buffer
Returns
True if everything was OK and false if data couldn't be stored
Reimplemented from base_text_serial.
Definition at line 741 of file sd_card.cpp.
References line_buffer, queue< qType, qIndexType, qSize >::num_items(), queue< qType, qIndexType, qSize >::put(), ready_to_send(), SD_LINE_BUF_SIZE, and transmit_now().
Referenced by puts().
void sd_card::puts (char const * str) virtual
This method writes all the characters in a string to the card buffer until it gets to the '\0' at the end. Warning: This function blocks until it's finished.
Parameters
str The string to be written
Reimplemented from base_text_serial.
Definition at line 768 of file sd_card.cpp.
References putchar().
bool sd_card::ready_to_send (void) virtual
This method checks if the card is ready, with a file opened, for some data to be sent to it. If a file is opened, the status flags will have been set properly.
Returns
True if there's a card ready for data and false if not
Reimplemented from base_text_serial.
Definition at line 724 of file sd_card.cpp.
References dir_file_result.
Referenced by putchar().
void sd_card::transmit_now (void) virtual
This method writes the data from the buffer to the card. Because there's so much data and flash cards are slow, it takes a comparatively long time to write data.
Reimplemented from base_text_serial.
Definition at line 780 of file sd_card.cpp.
References dir_file_result, queue< qType, qIndexType, qSize >::flush(), line_buffer, queue< qType, qIndexType, qSize >::num_items(), p_line_buffer, and the_file.
Referenced by close_file(), and putchar().
The documentation for this class was generated from the following files:
sd_card.h
sd_card.cpp