Polar Plotter Project: task_lines Class Reference
task_lines Class Reference
#include <task_lines.h>
Public Member Functions
task_lines (base_text_serial *p_serial_port, task_timer &a_timer, time_stamp &t_stamp, task_PID *PID_1, task_PID *PID_2, point *get_there, servo *PEN)
char run (char)
void go (void)
This method sets a bool allowing task_lines to operate.
void set_coords (int16_t X0, int16_t Y0, int16_t X_f, int16_t Y_f)
Set_coords updates the initial and final x&y coordinates when a new line needs to be drawn.
void draw_signature (void)
This method sets up lines to draw our signature.
bool wanna_go_home (void)
This method allows Go_Home to see if we want to home (after each line).
void ok_were_home (void)
This method allows Go_Home to lower the homing flag once home is reached.
Protected Attributes
base_text_serial * ptr_2_serial
pointer to a serial port object for printing purposes
point * Initial_Point
point object used to move machine
servo * operate_pen
servo object used to raise lower pen
task_PID * PID_1
PID object used to control motor 1.
task_PID * PID_2
PID object used to control motor 2.
bool send_home
boolean used to request homing
bool divide_lines
boolean which allows lines to begin
bool moving
boolean used to wait while movement occurs
bool signature
boolean used to initiate and continue signiture process
uint8_t sig_count
sub state variable keeps track of where in signiture we are
uint8_t line_type
sub state variable used to transition between line types
int8_t dx
incremental x distance in tenths of an inch
int8_t dy
incremental y distance in tenths of an inch
uint16_t current_segment
keeps track of when a line is done
uint16_t Seg_Total
total number of segments in a line
uint16_t counter
dumb counter used to let pen get down befor next step happens
int32_t SUMdx
total change in x
int32_t SUMdy
total change in y
int16_t x0
initial x coordinate of a line
int16_t y0
initial y coordinate of a line
int16_t xf
final x coordinate of a line
int16_t yf
final y coordinate of a line
float slope
to detect lines we can do really well! (through origin)
float SUMx_squared
partitioning pythagorean theorum helped math errors stop
float SUMy_squared
partitioning pythagorean theorum helped math errors stop
uint16_t SUMdx_16
extra variable to help avoid math errors
uint16_t SUMdy_16
extra variable to help avoid math errors
Detailed Description
task_lines.cpp is a task which cuts lines into bitty pieces and moves sequentially through the line by moving the setpoint and feeding it to the point task.
Definition at line 23 of file task_lines.h.
Constructor & Destructor Documentation
task_lines::task_lines (base_text_serial * p_serial_port, task_timer & a_timer, time_stamp & t_stamp, task_PID * motor_1, task_PID * motor_2, point * get_there, servo * PEN)
The constructor initializes variables, and saves object pointers locally.
Parameters
p_serial_port Serial object so we can write to screen
a_timer Time value used for STL scheduling
t_stamp Time stamp used for STL scheduling
motor_1 PID object for motor 1
motor_2 PID object for motor 2
get_there Point object used to move from setpoint to setpoint
PEN Servo Object to raise/lower pen
Definition at line 45 of file task_lines.cpp.
References divide_lines, Initial_Point, moving, operate_pen, PID_1, PID_2, ptr_2_serial, send_home, sig_count, signature, x0, xf, y0, and yf.
Member Function Documentation
char task_lines::run (char state)
run is the main method in task_lines. It takes care of the math involved in cutting a line into segments. It first takes the initial and final x&y coordinates, uses the pythagorean theorem to find the length of the actual line, determins how many segments to break the line up into based on it's overall length, calculates the slope of the line, and then uses the slope along with the change in the x&y coordinates to determine if the line passes through the origin (type 1), is vertical (type 2), is horizontal (type 4), or general and none of the above (type 3). The reason for categorizing what type of line you're drawing is because the algorithm is slightly different for each line type and certain lines can be drawn much faster by using a different algorithm, especially lines which pass through the origin. task_lines then breaks the line into smaller segments, keeps track of what segment the polar plotter is currently on, increments setpoints as each one is reached, and uses the point object to physically move the pen to the next setpoint. All of this is accomplished using a switch-case structure and flags which are raised and lowered depending on what needs to happen.
Parameters
state This method uses STL_task to transition its state
State 0 is a wait state. Is a new line requested?
State 1 does some initial x-y to r-theta calculations
State 2 starts movement towards initial point
State 3 waits for attainment of initial point
state 4 draws line which would pass through origin
state 5 draws vertical lines
state 6 draws general lines
state 7 draws horizontal lines
State 8 draws our signature!
State 9 sends the plotter home after each line in our signature
Definition at line 81 of file task_lines.cpp.
References point::Are_We_There(), counter, current_segment, divide_lines, dx, dy, servo::Fine_Line(), point::Get_There(), Initial_Point, line_type, moving, operate_pen, servo::Pen_Up(), PID_1, PID_2, Seg_Total, send_home, set_coords(), sig_count, signature, slope, task_PID::stop(), SUMdx, SUMdx_16, SUMdy, SUMdy_16, SUMx_squared, SUMy_squared, x0, xf, y0, and yf.
The documentation for this class was generated from the following files:
task_lines.h
task_lines.cpp