Polar Plotter Project: task_read Class Reference
task_read Class Reference
#include <task_read.h>
Public Member Functions
task_read (base_text_serial *p_serial_port, task_PID *motor_1, task_PID *motor_2, uint8_t *p_print_mode, Master *SPI, task_lines *LINES, servo *Tom_Servo, Go_Home *Home_Slice, point *POINTY)
void run (void)
Protected Attributes
base_text_serial * ptr_2_serial
This input driver class needs a pointer to the serial port used to echo inputs to the terminal.
task_PID * PID_1
this input driver class needs pointers to each PID object it is expected to interface with
task_PID * PID_2
this input driver class needs pointers to each PID object it is expected to interface with
Master * MASTER
this input driver class needs a pointer to the SPI master object for reset purposes
task_lines * MAKE_PATH
this input driver class needs a pointer to task_lines to initiate the coordinate conversion process
uint8_t * ptr_2_print_mode
print_mode is used in task_print to tell what to print and task_read to tell when printing is done
servo * You_Just_Got_Servoed
servo object allowing pen to be actuated
Go_Home * Plotter_Home
Go_Home object allows task_read to initiate homing procedure.
point * Make_Point
point object so make point operation can be initialized
bool coord_request
sets coordinate inpute mode to take 4 coords
bool point_request
sets coordinate inpute mode to take 2 coords
char input_char
buffer to store inputted char
uint8_t read_state
state variable for task_read
uint8_t read_mode
read_mode tells input states where to save to
uint16_t coordinate
temporary storage of a coordinate during conversion
uint32_t K
temporary storage of a gain value during conversion. (this gets typecasted to 16 bit at save)
uint8_t index
counts number of inputted digits and helps with decimal point logic for coordinates.
uint8_t dec_flag
helps in coordinate entry
uint16_t X0
initial x coordinate
uint16_t Y0
initial y coordinate
uint16_t X_f
final x coordinate or point x coordinate
uint16_t Y_f
final y coordinate or point y coordinate
uint8_t coord_num
keeps track of where to save what coordianate as they're entered
Detailed Description
task_read is the input section of the user interface for the polar plotter. It takes in the following commands: [h,H,?] print a help screen [o,O] home the machine [g,G] enable motor control [s,S] disable motor control (stop motors) [SPACE] Emergency stop [r,R] raise pen [l,L] lower pen [p,P] initiate K_p GAIN ENTRY MODE [i,I] initiate K_i GAIN ENTRY MODE [d,D] initiate K_d GAIN ENTRY MODE [c,C] initiate COORDINATE INPUT MODE to make a line [m,M] initiate COORDINATE INPUT MODE to make a point [q,Q] print current values of gains, encoders and set points [z,Z] reset PID controller (on both boards) [x,X] Make signiture COORDINATE INPUT MODES: Allows a user to enter values from 0 to 99.9 and accept one decimal place if desired GAIN ENTRY MODE: Allows a user to enter a number up to 5 digits. User is then promted on which motor to update. no enter key is required on this last step.
Definition at line 32 of file task_read.h.
Constructor & Destructor Documentation
task_read::task_read (base_text_serial * p_serial_port, task_PID * motor_1, task_PID * motor_2, uint8_t * p_print_mode, Master * Master_Object, task_lines * LINES, servo * Tom_Servo, Go_Home * Home_Slice, point * POINTY)
The constructor creates a task_read object which handles user inputs as described above. It takes in pointers to necessary objects and variables, saves them locally and initializes necessary variables. Of note, read_state and print_mode are initialized to 3 and 6 respectively so that the help menu will print out as soon as all constructors run.
Parameters
p_serial_port,: A pointer to the serial port for printing purposes
motor_1,: A pointer to a PID object
motor_2,: A pointer to a second PID object
p_print_mode,: A pointer to print_mode, which is a logic/state variable for print_state [TEMPORARY]
Master_Object,: A pointer to an SPI master object so resets can be performed
LINES A task_lines pointer so line endpoints can be set
Tom_Servo A servo object so pen can be raised/lowered
Home_Slice A Go_Home object so homing can be initiated
POINTY A point object so make a point command can be initiated
task_read is the input section of the user interface for the polar plotter. It takes in the following commands: [h,H,?] print a help screen [o,O] home the machine [g,G] enable motor control [s,S] disable motor control (stop motors) [SPACE] Emergency stop [r,R] raise pen [l,L] lower pen [p,P] initiate K_p GAIN ENTRY MODE [i,I] initiate K_i GAIN ENTRY MODE [d,D] initiate K_d GAIN ENTRY MODE [c,C] initiate COORDINATE INPUT MODE to make a line [m,M] initiate COORDINATE INPUT MODE to make a point [q,Q] print current values of gains, encoders and set points [z,Z] reset PID controller (on both boards) [x,X] Make signiture COORDINATE INPUT MODES: Allows a user to enter values from 0 to 99.9 and accept one decimal place if desired GAIN ENTRY MODE: Allows a user to enter a number up to 5 digits. User is then promted on which motor to update. no enter key is required on this last step.The constructor creates a task_read object which handles user inputs as described above. It takes in pointers to necessary objects and variables, saves them locally and initializes necessary variables. Of note, read_state and print_mode are initialized to 3 and 6 respectively so that the help menu will print out as soon as all constructors run.
Parameters
p_serial_port,: A pointer to the serial port for printing purposes
motor_1,: A pointer to a PID object
motor_2,: A pointer to a second PID object
p_print_mode,: A pointer to print_mode, which is a logic/state variable for print_state [TEMPORARY]
Master_Object,: A pointer to an SPI master object so resets can be performed
LINES A task_lines pointer so line endpoints can be set
Tom_Servo A servo object so pen can be raised/lowered
Home_Slice A Go_Home object so homing can be initiated
POINTY A point object so make a point command can be initiated
Definition at line 53 of file task_read.cpp.
References MAKE_PATH, Make_Point, MASTER, PID_1, PID_2, Plotter_Home, ptr_2_print_mode, ptr_2_serial, read_mode, read_state, and You_Just_Got_Servoed.
Member Function Documentation
void task_read::run (void)
the run method handles all user inputs. In easy cases, actions are taken here. in longer cases, states are used and flags indicate to another task, task_print, that a message should be printed to screen.
the run method handles all user inputs. In easy cases, actions are taken here. in longer cases, states are used and flags indicate to another task, task_print, that a message should be printed to screen. States are as follows: 0) Hub state: get char if input, check for valid command, initiate action 1) Coordinate entry mode 2) Gain value entry mode 3) Help Menu (wait for it to print) 4) Reset 5) Wait for coordinate value prompt 6) Wait for gain value prompt 7) Wait for prompt asking which motor to apply gain to 8) Apply entered to gain to correct memory location
State 0 is a hub state
State 1 is a coordinate entry mode. It expects a up to two digit integer with a tenths place decimal [ie 23.1 or 3.2]. it is always stored as number of tenths [ie 23.4 –> 234 here]
State 2 is an entry mode for gains. It expects an integer value up to 5 digits. Values are saturated to 16 bit maximum if entry is too large .
State 3 prints the help menu. Since that takes a bit the task waits until print out is done
State 4 is a user defined reset. Necessary motor control values are cleared on both microcontrollers
State 5 allows task_print enough time to get a prompt up before coordinate entry task is entered
State 6 allows task_print enough time to get a prompt up before gain entry task is entered
State 7 allows task_print enough time to ask which motor needs its gains adjusted before data is saved
State 8 saves gain information to the proper K location
State 9 initiates a command to make a dot
State 10 initiates a command to set the inital and final x&y coordinates for drawing a line
State 11 handles prompt printing wait times for coord entry
State 12 initiates a command to draw our custom signature
Definition at line 89 of file task_read.cpp.
References coord_num, coord_request, coordinate, dec_flag, task_lines::draw_signature(), servo::Fine_Line(), task_lines::go(), point::Go_Make_A_Dot(), index, input_char, K, MAKE_PATH, Make_Point, MASTER, servo::Pen_Up(), PID_1, PID_2, Plotter_Home, point_request, ptr_2_print_mode, ptr_2_serial, read_mode, read_state, task_PID::Request_Home(), task_lines::set_coords(), Go_Home::SET_Home_Request(), task_PID::stop(), X0, X_f, Y0, Y_f, and You_Just_Got_Servoed.
The documentation for this class was generated from the following files:
task_read.h
task_read.cpp