Polar Plotter Project: point Class Reference
point Class Reference
Public Member Functions
point (base_text_serial *p_serial_port, task_PID *motor_1, task_PID *motor_2, servo *Penny_Thingy)
void run (void)
void Get_There (uint16_t Xcoord, uint16_t Ycoord)
bool Are_We_There (void)
this method allows someone to check if we're there yet.
void Go_Make_A_Dot (uint16_t Xcoord, uint16_t Ycoord)
Protected Attributes
base_text_serial * ptr_2_serial
task_PID * PID_1
task_PID * PID_2
servo * Pen_Servo
bool Go_To
puts point into go-to mode
bool Make_Point
puts point into make-point mode
uint16_t counting
counting variable used to ensure pen gets down
uint8_t point_state
state variable
int16_t X
x coordinate desired
int16_t Y
y coordinate desired
int32_t encoder_now_theta
current THETA value in ticks
int32_t encoder_goal_theta
desired THETA value in ticks
int32_t encoder_now_r
current R value in ticks
int32_t encoder_goal_r
desired R value in ticks
float x_squared
allow pythagorean theorum without data loss
float y_squared
allow pythagorean theorum without data loss
Detailed Description
Definition at line 13 of file point.h.
Constructor & Destructor Documentation
point::point (base_text_serial * p_serial_port, task_PID * motor_1, task_PID * motor_2, servo * Penny_Thingy)
The constructor saves object pointers locally and initializes necessary variables.
Parameters
p_serial_port,: A pointer to the serial port for printing purposes
motor_1,: A pointer to a motor object
motor_2,: A pointer to a second motor object
Penny_Thingy,: A servo object used to move a pen
Definition at line 33 of file point.cpp.
References Go_To, Make_Point, and point_state.
Member Function Documentation
void point::Get_There (uint16_t Xcoord, uint16_t Ycoord)
This method initiates a cairrage go to. This is how lines moves the pen around.
Parameters
Xcoord,: An x coordinate to go to
Ycoord,: An y coordinate to go to
Definition at line 136 of file point.cpp.
References Go_To, X, and Y.
Referenced by task_lines::run().
void point::Go_Make_A_Dot (uint16_t Xcoord, uint16_t Ycoord)
This method initiates a go to and then makes a point there.
Parameters
Xcoord,: An x coordinate to go to
Ycoord,: An y coordinate to go to
Definition at line 154 of file point.cpp.
References Make_Point, X, and Y.
Referenced by task_read::run().
void point::run (void)
The run method moves the pen to a specific location. It has two modes. It can just move the pen somewhere or it can move the pen somewhere and then make a dot.
State 0 is a wait state. Is a point or move requested?
State 1 checks if correct location is achieved yet, if so, make dot if necessary
State 2 allows time for pen to move to the down position
Definition at line 56 of file point.cpp.
References task_PID::At_Seg_End(), counting, encoder_goal_r, encoder_goal_theta, servo::Fine_Line(), task_PID::go(), Go_To, Make_Point, servo::Pen_Up(), point_state, task_PID::set_setpoint(), task_PID::stop(), X, x_squared, Y, and y_squared.
The documentation for this class was generated from the following files:
point.h
point.cpp