Polar Plotter Project: stl_task Class Reference
stl_task Class Reference
#include <stl_task.h>
Public Member Functions
stl_task (task_timer &, const time_stamp &)
void set_interval (const time_stamp &)
void set_next_run_time (const time_stamp &)
virtual task_op_state schedule (time_stamp *=NULL)
virtual char run (char)
void suspend (void)
void resume (void)
void set_initial_state (char)
char get_serial_number (void)
char get_current_state (void)
task_op_state get_op_state (void)
void run_again_ASAP (void)
bool ready (void)
void error_stop (char const *)
Protected Attributes
task_timer & the_timer
This is a reference to the device driver which keeps track of real time.
time_stamp next_run_time
This is the time at which the task should next be run.
time_stamp interval
This is the time interval between runs of the task.
Detailed Description
This class implements the behavior of a task in the context of a multitasking system. Each task runs "simultaneously" with other tasks. This means, of course, that execution switches quickly from one task to another quite quickly under the control of the main execution scheduler. Since a task can be in any of several states at a given time, a task object will have a list of state methods which can be run and be able to switch between those states.
Usage
The programmer uses this class by deriving a descendent class from it. Then s/he creates a run() method in the new class which implements the states. In the run() method, there's a big switch statement which chooses which state code is to run when the run() method is called. Checking the time and deciding when to run is taken care of by the schedule() method, which only runs the task's state code when the task's time interval has been reached; if the time interval is set to 0, the state code is run every time run() is called. State transitions are detected and tracked by this class for testing and debugging purposes.
Options
Serial port debugging can be enabled by defining SERIAL_DEBUG and calling the constructor which is given a pointer to a uart object. The task will then write information about state transitions to the serial port during operation. This option is intended to be used during debugging, then turned off for production code, as serial device writing takes up time and memory, and of course it requires a serial device to be present and connected.
Execution time profiling can be enabled by defining STL_PROFILE. This option causes the execution times of the state functions to be measured and a simple set of performance data to be kept. Performance data can be written to a serial port at a convenient time, generally after the system has been run in test for a while.
Internal Organization
At any time, a task is in both a user state and an operational state. The user state is the state which the user manipulates; it chooses the action that the run() method will take each time it is called by the scheduler. The user state is the state which appears in the user's state transition diagrams. The operational state shows how the scheduler is treating a task - whether the task is running, waiting for its time to run, ready to run, suspended, etc. Operational states for all tasks follow the "state diagram" below.
Blocked tasks (due to resource contention) are not currently implemented.
When a task is run cooperatively (rather than by interrupts), it is run when the method schedule() is called from within the main while loop in the main() routine. The schedule() method belongs to class stl_task and generally does not need to be modified by the user.
Definition at line 121 of file stl_task.h.
Constructor & Destructor Documentation
stl_task::stl_task (task_timer & a_timer, const time_stamp & time_interval)
This constructor creates a task object. It must be called by the constructor of each task which is written by the user. This constructor sets the time between runs of the run() method (a timestamp with zero time can be used if a task needs to run via interrupt, or every single time its schedule() method is called). This constructor also saves a pointer to the serial port or radio object which will be used to dump debugging information, if serial debugging is being used.
Parameters
a_timer A reference to the timer which measures real-time intervals
time_interval The time between runs of the task's run() method
Definition at line 54 of file stl_task.cpp.
References endl, GLOB_DEBUG, PMS, and TASK_WAITING.
Member Function Documentation
void stl_task::error_stop (char const * message)
This method displays a message (if the program was compiled with serial debugging enabled) and then causes the processor to freeze in an infinite loop. It should be used if something awful happened and the safest thing to do is to just stop. Only use this function if there isn't a reasonable way to write an error state which handles exceptions in a more useful manner, such as by turning motors and other possibly dangerous devices off and then halting.
Parameters
message The text to be displayed before the processor stops working
Definition at line 258 of file stl_task.cpp.
References endl, GLOB_DEBUG, and PMS.
Referenced by schedule().
char stl_task::get_current_state (void) inline
This method returns the state in which the task is currently. The state cannot directly be changed by the user; it can only be changed through the returned value from the run() method.
Returns
The state in which the task is when this method is called
Definition at line 177 of file stl_task.h.
task_op_state stl_task::get_op_state (void) inline
This method returns the task's current operational state. The operational state isn't the same as the state transition logic state; it's a separate variable which controls if the task is running at a given time.
Returns
The task's current operational state
Definition at line 184 of file stl_task.h.
char stl_task::get_serial_number (void) inline
This method returns the task's automatically assigned serial number.
Returns
The task's serial number
Definition at line 170 of file stl_task.h.
Referenced by operator<<().
bool stl_task::ready (void) inline
This method tells whether the task needs to run again as soon as possible or not. It is convenient to use when determining if the processor should be put to sleep for a while.
Returns
True if the task needs to run soon, false if it does not
Definition at line 196 of file stl_task.h.
References TASK_PENDING, and TASK_RUNNING.
void stl_task::resume (void)
This method resumes the task from suspension, so that the task can run again. The operational state which was saved at the time of suspension is restored.
Definition at line 229 of file stl_task.cpp.
char stl_task::run (char a_state) virtual
This is a base method which the user should overload in each descendent of this task class. The run method is where all the user-defined action in the task takes place. It is either called by the task's schedule() method, in the case of cooperative multitasking, or by an interrupt handler, in the case of pre-emptive multitasking.
Parameters
a_state The state of the task when this run method begins running
Returns
The state to which the task will transition, or STL_NO_TRANSITION if no transition is called for at this time
Reimplemented in task_PID, task_lines, and Go_Home.
Definition at line 203 of file stl_task.cpp.
References endl, GLOB_DEBUG, PMS, and STL_NO_TRANSITION.
Referenced by schedule().
void stl_task::run_again_ASAP (void) inline
This method will cause the task to run again as soon as it can instead of waiting for the given time interval.
Definition at line 189 of file stl_task.h.
References TASK_PENDING.
task_op_state stl_task::schedule (time_stamp * til_next_time = NULL) virtual
This method is called by the main task loop to try to run the task. If the task is in the waiting state, it checks to see if it's time to run yet; if it's in the suspended state, it doesn't. The task shouldn't be in the running state, because this method is used by the cooperative scheduler, not the pre-emptive one.
Parameters
til_next_time A pointer to a time stamp which will hold next time this task next needs to run, or NULL (default) if this data isn't needed
Returns
The operational state of the task after it has been given this chance to run
Definition at line 115 of file stl_task.cpp.
References endl, error_stop(), task_timer::get_time_now(), GLOB_DEBUG, interval, next_run_time, run(), STL_NO_TRANSITION, TASK_PENDING, TASK_SUSPENDED, TASK_WAITING, and the_timer.
void stl_task::set_initial_state (char init_state)
This method changes the initial state in which the task begins to operate. The default initial state is state 0. It should only be used before the task begins to run, as it sets the current and next state variables and will completely mess up normal state transition operation if called at any other time.
Definition at line 242 of file stl_task.cpp.
void stl_task::set_interval (const time_stamp & time_interval)
This method sets or changes the time interval between runs of this task.
Parameters
time_interval The time between runs of the task's run() method
Definition at line 83 of file stl_task.cpp.
References interval.
void stl_task::set_next_run_time (const time_stamp & next_time)
This method sets the next run time for the task. It should be used if the task timer's value is adjusted significantly, or if the task timer is started at a time long after time zero. If this isn't done, the task will run many times in quick succession, trying to catch up to the correct run time. Note that if this method is called and sets the next time far in the past, the same problem will occur.
Parameters
next_time A time stamp containing the next time for the task to run
Definition at line 98 of file stl_task.cpp.
References next_run_time.
void stl_task::suspend (void)
This method suspends the task so that it won't run again until after somebody calls the resume() method. The state of the task before suspension is saved so that it can be restored after suspension.
Definition at line 217 of file stl_task.cpp.
References TASK_SUSPENDED.
The documentation for this class was generated from the following files:
stl_task.h
stl_task.cpp