Polar Plotter Project: task_PID Class Reference
task_PID Class Reference
#include <task_PID.h>
Public Member Functions
task_PID (base_text_serial *p_serial_port, task_timer &a_timer, time_stamp &t_stamp, Master *master_object, da_motor *motor_object, uint8_t which_Channel)
char run (char)
void go (void)
void stop (void)
void CLEAR (void)
void set_kp (uint16_t kp_val)
set K_p
void set_ki (uint16_t ki_val)
set K_i
void set_kd (uint16_t kd_val)
set K_d
uint16_t GET_Kp (void)
GET_Kp returns K_p.
uint16_t GET_Ki (void)
GET_Ki returns K_i.
uint16_t GET_Kd (void)
GET_Kd returns K_d.
void set_setpoint (int32_t s_pt)
int32_t GET_setpoint (void)
int32_t Get_Encoder (void)
bool At_Seg_End (void)
void Request_Home (bool Nice_Shoes)
Protected Attributes
base_text_serial * ptr_2_serial
pointer to a serial port object for printing purposes
Master * func_READ_ENCODER
pointer of type Master to an SPI object
da_motor * func_UPDATE_MOTOR
pointer of type da_motor to a motor object
bool giddyup
tell motor to stop or go
bool homing
homing allows task Go_Home to take control of motors
uint8_t motor_num
a constant for each PID which controls which motor and encoder we use each time the PID is called
uint8_t Checksum_Error_flag
A flag which indicates an SPI transfer error.
volatile uint8_t dummy
stupid counting variable
uint8_t duty_cycle
name pretty well says it
uint16_t K_p
proportional gain
uint16_t K_i
integral gain
uint16_t K_d
differential gain
int32_t prev_error
used for differential feedback
int32_t E_sum_old
used for integral feedback
int32_t encoder
encoder reading
int32_t Set_Point
the set point
bool are_we_there_yet
boolean set to true when desired position is reached
Detailed Description
task_PID.cpp is a class for a PID controller. task_PID is able to read the current encoder position on a motor, calculate the proportional, integral, and differential gains, and update the motor's duty cycle based on the final gain value. It can also manipulate certain flags via inline functions to trigger actions, such as telling a motor to go or stop, in other objects.
Definition at line 22 of file task_PID.h.
Constructor & Destructor Documentation
task_PID::task_PID (base_text_serial * p_serial_port, task_timer & a_timer, time_stamp & t_stamp, Master * master_object, da_motor * motor_object, uint8_t Which_Channel)
The constructor task_PID creates a new PID object.
Parameters
p_serial_port Allows screen printouts
a_timer,: Assists in sceduling
t_stamp,: Assists in sceduling
master_object An SPI master object
motor_object,: A motor object
Which_Channel,: Gives the newborn PID its motor assignment. For life.
The constructor task_PID creates a new Proportional Integral Differential (PID) controller object.
Parameters
p_serial_port Allows screen printouts
a_timer,: Assists in sceduling
t_stamp,: Assists in sceduling
master_object An SPI master object
motor_object,: A motor object
Which_Channel,: Gives the newborn PID its motor assignment. For life.
Definition at line 40 of file task_PID.cpp.
References are_we_there_yet, duty_cycle, E_sum_old, encoder, func_READ_ENCODER, func_UPDATE_MOTOR, giddyup, homing, K_d, K_i, K_p, motor_num, prev_error, ptr_2_serial, and Set_Point.
Member Function Documentation
bool task_PID::At_Seg_End (void) inline
check if we're at the end of the segment
Definition at line 117 of file task_PID.h.
References are_we_there_yet.
Referenced by point::run().
void task_PID::CLEAR (void)
CLEAR resets PID control variables
Definition at line 192 of file task_PID.cpp.
References duty_cycle, E_sum_old, encoder, and prev_error.
Referenced by Go_Home::run().
int32_t task_PID::Get_Encoder (void) inline
Get_Encoder gets an encoder reading
Definition at line 113 of file task_PID.h.
References encoder.
Referenced by run().
int32_t task_PID::GET_setpoint (void) inline
GET_setpoint gets the current setpoint so it can be printed
Parameters
Set_Point the set point you desire
Definition at line 109 of file task_PID.h.
References Set_Point.
void task_PID::go (void)
go enables motor control
Definition at line 177 of file task_PID.cpp.
References are_we_there_yet, and giddyup.
Referenced by point::run().
void task_PID::Request_Home (bool Nice_Shoes) inline
disable PID so homing can occur
Parameters
Nice_Shoes set this true to disable PID for homing
Definition at line 122 of file task_PID.h.
References homing.
Referenced by Go_Home::run(), and task_read::run().
char task_PID::run (char state)
run is a 2 state PID controller. State 0 is an idle state which wits for the go bool giddyup to be true. State 1 gets an encoder count, does necessary feedback calculations and sets motor duty cycle.
Parameters
state is a state variable controlled by STL_task
run is a two state PID controller. The first state is simply a non moving state which checks to see if movement has been requested. State two incorporates proportional, integral and differential feedback into a control loop which updates the duty cycle of a motor (one motor per PID object).
State 0 is a non moving state. It doesn't move.
State 1 is the PID task. It gets a current encoder reading (ensuring no transfer error) and then calculates new duty and sets the duty cycle.
Definition at line 72 of file task_PID.cpp.
References are_we_there_yet, Checksum_Error_flag, dummy, duty_cycle, E_sum_old, encoder, func_READ_ENCODER, func_UPDATE_MOTOR, Get_Encoder(), giddyup, homing, K_i, K_p, motor_num, prev_error, da_motor::set_mode(), Set_Point, and da_motor::update_duty_cycle().
void task_PID::set_kd (uint16_t kd_val) inline
set K_d
Parameters
kd_val,: the value you wish to set the gain to
Definition at line 91 of file task_PID.h.
References K_d.
void task_PID::set_ki (uint16_t ki_val) inline
set K_i
Parameters
ki_val,: the value you wish to set the gain to
Definition at line 89 of file task_PID.h.
References K_i.
void task_PID::set_kp (uint16_t kp_val) inline
set K_p
Parameters
kp_val,: the value you wish to set the gain to
Definition at line 87 of file task_PID.h.
References K_p.
void task_PID::set_setpoint (int32_t s_pt) inline
set_setpoint sets the setpoint
Parameters
s_pt the set point you desire
Definition at line 104 of file task_PID.h.
References are_we_there_yet, and Set_Point.
Referenced by point::run().
void task_PID::stop (void)
stop disables motor control (stops the motors)
Definition at line 185 of file task_PID.cpp.
References are_we_there_yet, and giddyup.
Referenced by point::run(), task_lines::run(), and task_read::run().
The documentation for this class was generated from the following files:
task_PID.h
task_PID.cpp