Polar Plotter Project: Go_Home Class Reference
Go_Home Class Reference
#include <Go_Home.h>
Public Member Functions
Go_Home (base_text_serial *, task_timer &, time_stamp &, da_motor *, Master *, task_PID *, task_PID *, task_lines *)
char run (char state)
void SET_Home_Request (void)
bool Is_Home (void)
Protected Attributes
base_text_serial * ptr_2_serial
da_motor * Vtec_wins
Master * Wipe_Slave
task_PID * Wipe_Master1
task_PID * Wipe_Master2
task_lines * LINES
Detailed Description
Go_Home.cpp is a class with methods to send the carriage and arm to their home positions and reset both motor encoders. Two bump-stop switches connected to pin interrupts tell the microcontroller to stop the motors when the carriage and arm reach their respective home positions.
Definition at line 23 of file Go_Home.h.
Constructor & Destructor Documentation
Go_Home::Go_Home (base_text_serial * p_serial_port, task_timer & a_timer, time_stamp & t_stamp, da_motor * Vortec, Master * Clear_Slave, task_PID * Clear_Master1, task_PID * Clear_Master2, task_lines * liner)
This constructor enables the interrupts necessary for the bump stop switches on our plotter to operate, initializes control booleans, and saves object pointers locally.
Parameters
p_serial_port Allows screen printouts
a_timer,: A Timer object to assist with sceduling
t_stamp,: A Time Stamp object to assist with sceduling
Vortec,: A motor object
Clear_Slave An SPI master object
Clear_Master1 PID object for motor 1
Clear_Master2 PID object for motor 2
liner task lines object so it can call home
Definition at line 44 of file Go_Home.cpp.
Member Function Documentation
bool Go_Home::Is_Home (void)
Is_Home returns a flag which is true if machine is done homing.
Definition at line 154 of file Go_Home.cpp.
References Home_Request.
char Go_Home::run (char state)
run is the main method in Go_Home and it performs the actual homing operation of the 2 degree of freedom system.
Parameters
state,: STL_task is used for scheduling
State 0 does nothing unless homing is requested by user key press or task_lines
State 1 initiates movement of the arm towards home if cart has reached r=0
State 2 concludes homing once arm reaches THETA=0.
Definition at line 71 of file Go_Home.cpp.
References arm_switch, cart_switch, Master::CLEAR(), task_PID::CLEAR(), Home_Request, task_lines::ok_were_home(), task_PID::Request_Home(), da_motor::set_mode(), da_motor::update_duty_cycle(), and task_lines::wanna_go_home().
void Go_Home::SET_Home_Request (void)
SET_Home_Request allows homing to be initiated by other tasks
Definition at line 147 of file Go_Home.cpp.
References Home_Request.
Referenced by task_read::run().
The documentation for this class was generated from the following files:
Go_Home.h
Go_Home.cpp