Polar Plotter Project: base_text_serial Class Reference
base_text_serial Class Reference
#include <base_text_serial.h>
Public Member Functions
base_text_serial (void)
virtual bool ready_to_send (void)
virtual bool putchar (char)
Virtual and not defined in base class.
virtual void puts (char const *)
Virtual and not defined in base class.
virtual bool check_for_char (void)
virtual char getchar (void)
virtual void transmit_now (void)
virtual void clear_screen (void)
base_text_serial & operator<< (bool)
base_text_serial & operator<< (const char *)
base_text_serial & operator<< (unsigned char)
base_text_serial & operator<< (char num)
base_text_serial & operator<< (unsigned int)
base_text_serial & operator<< (int)
base_text_serial & operator<< (unsigned long)
base_text_serial & operator<< (long)
base_text_serial & operator<< (unsigned long long)
base_text_serial & operator<< (ser_manipulator)
Protected Attributes
unsigned char base
This is the currently used base for converting numbers to text.
bool print_ascii
bool pgm_string
char precision
Detailed Description
This is a base class for lots of serial devices which send text over some type of communication interface. Descendents of this class will be able to send text over serial lines, radio modems or modules, and whatever other communication devices might be appropriate.
The most important methods of this class are the overloaded "<<" operators which convert different types of numbers into printable strings, then print them using methods which are overloaded by descendent classes. Methods are provided which transmit most types of integers and floating point numbers; floating point numbers are only handled if <math.h> is defined near the beginning of base_text_serial.h because one often wants to turn off floating point support in order to save memory. Other classes may implement methods to print themselves to any descendent of this class; see stl_timer.h/cc for examples in which time stamps print the time conveniently to any serial device.
The ability to transmit characters is provided by descendent classes. Methods which will be inherited or overridden by descendents include the following:
ready_to_send () - Checks if the port is ready to transmit a character
putchar() - Sends a single character over the communications line
puts() - Sends a character string Other methods may optionally be overridden; for example clear_screen() is only needed by devices which have a screen, and some devices may be read-only or write-only, and some methods may not be needed.
Definition at line 172 of file base_text_serial.h.
Constructor & Destructor Documentation
base_text_serial::base_text_serial (void)
This constructor sets up the base serial port object. It sets the default base for the conversion of numbers to text and the default format for converting chars.
Definition at line 55 of file base_text_serial.cpp.
References base, pgm_string, precision, and print_ascii.
Member Function Documentation
bool base_text_serial::check_for_char (void) virtual
This method checks if there is a character in the serial port's receiver buffer. There isn't, as this base class isn't connected to a buffer; descendent classes will override this method and check a real buffer for real characters.
Returns
False, because no character will ever be available
Reimplemented in rs232.
Definition at line 97 of file base_text_serial.cpp.
Referenced by task_read::run().
void base_text_serial::clear_screen (void) virtual
This is a base method to clear a display screen, if there is one. It is called when the format modifier 'clrscr' is inserted in an output line. Descendant classes which send things to displays should respond by clearing themselves.
Reimplemented in rs232.
Definition at line 121 of file base_text_serial.cpp.
Referenced by operator<<().
char base_text_serial::getchar (void) virtual
This base method just returns zero, because it shouldn't be called. There might be classes which only send characters and don't ever receive them, and this method could be left as a placeholder for those classes.
Returns
A zero (null character) which means nothing
Reimplemented in rs232.
Definition at line 84 of file base_text_serial.cpp.
Referenced by task_read::run().
base_text_serial & base_text_serial::operator<< (bool value)
This method writes a boolean value to the serial port as a character, either "T" or "F" depending on the value.
Parameters
value The boolean value to be written
Definition at line 161 of file base_text_serial.cpp.
References putchar().
base_text_serial & base_text_serial::operator<< (const char * string)
This method writes the string whose first character is pointed to by the given character pointer to the serial device. It acts in about the same way as puts(). As with puts(), the string must have a null character (ASCII zero) at the end.
Parameters
string Pointer to the string to be written
Definition at line 133 of file base_text_serial.cpp.
References pgm_string, and putchar().
base_text_serial & base_text_serial::operator<< (unsigned char num)
This method writes a character to the serial port as a text string showing the 8-bit unsigned number in that character. If the format control term 'ascii' was called prior to this printing, the character will be printed as an ASCII character.
Parameters
num The 8-bit number or character to be sent out
Definition at line 179 of file base_text_serial.cpp.
References base, print_ascii, putchar(), and puts().
base_text_serial & base_text_serial::operator<< (char num)
This method writes a character to the serial port as a text string showing the 8-bit signed number in that character, unless the 'ascii' manipulator has been used to put the port in ascii text mode, in which case the character is printed directly.
Parameters
num The 8-bit number to be sent out
Definition at line 221 of file base_text_serial.cpp.
References base, print_ascii, putchar(), and puts().
base_text_serial & base_text_serial::operator<< (unsigned int num)
This method writes an integer to the serial port as a text string showing the 16-bit unsigned number in that integer.
Parameters
num The 16-bit number to be sent out
Definition at line 248 of file base_text_serial.cpp.
References base, and puts().
base_text_serial & base_text_serial::operator<< (int num)
This method writes an integer to the serial port as a text string showing the 16-bit signed number in that integer.
Parameters
num The 16-bit number to be sent out
Definition at line 276 of file base_text_serial.cpp.
References base, and puts().
base_text_serial & base_text_serial::operator<< (unsigned long num)
This method writes an unsigned long integer to the serial port as a text string showing the 32-bit unsigned number in that long integer.
Parameters
num The 32-bit number to be sent out
Definition at line 300 of file base_text_serial.cpp.
References base, and puts().
base_text_serial & base_text_serial::operator<< (long num)
This method writes a long integer to the serial port as a text string showing the 32-bit signed number in that long integer.
Parameters
num The 32-bit number to be sent out
Definition at line 328 of file base_text_serial.cpp.
References base, and puts().
base_text_serial & base_text_serial::operator<< (unsigned long long num)
This method writes a long long (64-bit) unsigned integer to the serial port as a text string. It only writes such numbers in unsigned hexadecimal format. The number is written by breaking it into two unsigned longs, writing them in order.
Parameters
num The 64-bit number to be sent out
Definition at line 352 of file base_text_serial.cpp.
base_text_serial & base_text_serial::operator<< (ser_manipulator new_manip)
This overload allows manipulators to be used to change the base of displayed numbers to binary, octal, decimal, or hexadecimal. Also, and endline is provided with the name "endl" and the code "send_now" causes immediate transmission by devices which save stuff to be transmitted in buffers.
Parameters
new_manip The serial manipulator which was given
Definition at line 479 of file base_text_serial.cpp.
References _p_str, ascii, base, bin, clear_screen(), clrscr, dec, endl, ENDL_STYLE, hex, numeric, oct, pgm_string, print_ascii, puts(), send_now, and transmit_now().
bool base_text_serial::ready_to_send (void) virtual
This function checks if the serial port transmitter is ready to send data. It's an empty base method, overridden by most serial devices. Some serial devices might always be ready to send data; those can not bother to override this method.
Returns
True if the serial port is ready to send, and false if not
Reimplemented in sd_card.
Definition at line 71 of file base_text_serial.cpp.
void base_text_serial::transmit_now (void) virtual
This is a base method for causing immediate transmission of a buffer full of data. The base method doesn't do anything, because it will be implemented in descendent classes which have no buffers, send everything immediately by default, and don't need to respond to calls for immediate transmission.
Reimplemented in sd_card.
Definition at line 110 of file base_text_serial.cpp.
Referenced by operator<<().
Member Data Documentation
bool base_text_serial::pgm_string protected
If this variable is true, the next string to be printed will be found in program (flash) memory, not data memory.
Definition at line 190 of file base_text_serial.h.
Referenced by base_text_serial(), and operator<<().
char base_text_serial::precision protected
This is the number of digits after a decimal point to be printed when a floating point number is being converted to text.
Definition at line 194 of file base_text_serial.h.
Referenced by base_text_serial().
bool base_text_serial::print_ascii protected
If this variable is set true, print characters as ASCII characters, not as numbers.
Definition at line 186 of file base_text_serial.h.
Referenced by base_text_serial(), and operator<<().
The documentation for this class was generated from the following files:
base_text_serial.h
base_text_serial.cpp