Polar Plotter Project: rs232 Class Reference
rs232 Class Reference
#include <rs232int.h>
Public Member Functions
rs232 (unsigned int=9600, unsigned char=0)
bool putchar (char)
This method writes one character to the serial port.
void puts (char const *)
bool check_for_char (void)
char getchar (void)
void clear_screen (void)
Public Member Functions inherited from base_text_serial
base_text_serial (void)
virtual bool ready_to_send (void)
virtual void transmit_now (void)
base_text_serial & operator<< (bool)
base_text_serial & operator<< (const char *)
base_text_serial & operator<< (unsigned char)
base_text_serial & operator<< (char num)
base_text_serial & operator<< (unsigned int)
base_text_serial & operator<< (int)
base_text_serial & operator<< (unsigned long)
base_text_serial & operator<< (long)
base_text_serial & operator<< (unsigned long long)
base_text_serial & operator<< (ser_manipulator)
Public Member Functions inherited from base232
base232 (unsigned int=9600, unsigned char=0)
The constructor sets up the port with the given baud rate and port number.
bool ready_to_send (void)
This method checks if the serial port is ready to transmit data.
bool is_sending (void)
This method returns true if the port is currently sending a character out.
Protected Attributes
uint8_t port_num
The USART number, 0 or 1.
Protected Attributes inherited from base_text_serial
unsigned char base
This is the currently used base for converting numbers to text.
bool print_ascii
bool pgm_string
char precision
Protected Attributes inherited from base232
volatile unsigned char * p_UDR
This is a pointer to the data register used by the UART.
volatile unsigned char * p_USR
This is a pointer to the status register used by the UART.
volatile unsigned char * p_UCR
This is a pointer to the control register used by the UART.
unsigned char mask_UDRE
This bitmask identifies the bit for data register empty, UDRE.
unsigned char mask_RXC
This bitmask identifies the bit for receive complete, RXC.
unsigned char mask_TXC
This bitmask identifies the bit for transmission complete, TXC.
Detailed Description
This class controls a UART (Universal Asynchronous Receiver Transmitter), a common serial interface. It talks to old-style RS232 serial ports (through a voltage converter chip such as a MAX232) or through a USB to serial converter such as a FT232RL chip. The UART is also sometimes used to communicate directly with other microcontrollers, sensors, or wireless modems.
Definition at line 68 of file rs232int.h.
Constructor & Destructor Documentation
rs232::rs232 (unsigned int baud_rate = 9600, unsigned char port_number = 0)
This method sets up the AVR UART for communications. It calls the base_text_serial constructor, which prepares to convert numbers to text strings, and the base232 constructor, which does the work of setting up the serial port. Note that the user program must call sei() somewhere to enable global interrupts so that this driver will work. It is not called in this constructor because it's common to construct many drivers which use interrupts, including this one, and then enable interrupts globally using sei() after all the constructors have been called.
Parameters
baud_rate The desired baud rate for serial communications. Default is 9600
port_number The number of the serial port, 0 or 1 (the second port numbered 1 only exists on some processors). The default is port 0
Definition at line 75 of file rs232int.cpp.
References port_num, rcv0_buffer, rcv0_read_index, rcv0_write_index, and RSINT_BUF_SIZE.
Member Function Documentation
bool rs232::check_for_char (void) virtual
This method checks if there is a character in the serial port's receiver queue. The queue will have been filled if a character came in through the serial port and caused an interrupt. It returns 1 if there's a character available, and 0 if not.
Returns
True for character available, false for no character available
Reimplemented from base_text_serial.
Definition at line 218 of file rs232int.cpp.
References port_num, rcv0_read_index, and rcv0_write_index.
void rs232::clear_screen (void) virtual
This method sends the ASCII code to clear a display screen. It is called when the format modifier 'clrscr' is inserted in a line of "<<" stuff.
Reimplemented from base_text_serial.
Definition at line 236 of file rs232int.cpp.
References CLRSCR_STYLE, and putchar().
char rs232::getchar (void) virtual
This method gets one character from the serial port, if one is there. If not, it waits until there is a character available. This can sometimes take a long time (even forever), so use this function carefully. One should almost always use check_for_char() to ensure that there's data available first.
Returns
The character which was found in the serial port receive buffer
Reimplemented from base_text_serial.
Definition at line 177 of file rs232int.cpp.
References port_num, rcv0_buffer, rcv0_read_index, rcv0_write_index, and RSINT_BUF_SIZE.
bool rs232::putchar (char chout) virtual
This method writes one character to the serial port.
This method sends one character to the serial port. It waits until the port is ready, so it can hold up the system for a while. It times out if it waits too long to send the character; you can check the return value to see if the character was successfully sent, or just cross your fingers and ignore the return value. Note 1: It's possible that at slower baud rates and/or higher processor speeds, this routine might time out even when the port is working fine. A solution would be to change the count variable to an integer and use a larger starting number. Note 2: Fixed! The count is now an integer and it works at lower baud rates.
Parameters
chout The character to be sent out
Returns
True if everything was OK and false if there was a timeout
Reimplemented from base_text_serial.
Definition at line 137 of file rs232int.cpp.
References base232::mask_TXC, base232::mask_UDRE, base232::p_UDR, base232::p_USR, and UART_TX_TOUT.
Referenced by clear_screen(), and puts().
void rs232::puts (char const * str) virtual
This method writes all the characters in a string until it gets to the '\0' at the end. Warning: This function blocks until it's finished.
Parameters
str The string to be written
Reimplemented from base_text_serial.
Definition at line 163 of file rs232int.cpp.
References putchar().
The documentation for this class was generated from the following files:
rs232int.h
rs232int.cpp