Polar Plotter Project: queue< qType, qIndexType, qSize > Class Template Reference
queue< qType, qIndexType, qSize > Class Template Reference
These defines prevent this file from being included more than once in a *.cc file.
#include <queue.h>
Public Member Functions
queue (void)
bool put (qType)
bool jam (qType)
qType get (void)
bool is_empty (void)
void flush (void)
qType operator[] (qIndexType)
qIndexType num_items (void)
qType * get_p_buffer (void)
Protected Attributes
qType buffer [qSize]
This memory buffer holds the contents.
qIndexType i_put
Index where newest data will be written.
qIndexType i_get
Index where oldest data was written.
qIndexType how_full
How many elements are full at this time.
Detailed Description
template<class qType, class qIndexType, qIndexType qSize>
class queue< qType, qIndexType, qSize >
These defines prevent this file from being included more than once in a *.cc file.
This class implements a simple queue. As a template class, it can be used to create queues which hold any type of object whose data is copied in with an assignment operator. The size and type of object are determined at compile time for efficiency.
Definition at line 49 of file queue.h.
Constructor & Destructor Documentation
template<class qType , class qIndexType , qIndexType qSize> queue< qType, qIndexType, qSize >::queue (void)
This constructor creates a queue item. Note that it doesn't have to allocate memory because that was already done statically by the template mechanism at compile time. If no parameters are supplied, a 16-element queue for characters which uses 8-bit array indices (for a maximum of 255 elements) is created. The template parameters are as follows:
qType: The type of data which will be stored in the queue (default char)
qIndexType: The type of data used for array indices
qSize: The number of items in the queue's memory buffer (default 16)
Definition at line 93 of file queue.h.
Member Function Documentation
template<class qType , class qIndexType , qIndexType qSize> void queue< qType, qIndexType, qSize >::flush (void)
This method empties the buffer. It doesn't actually erase everything; it just sets the indices and fill indicator all to zero as if the buffer contained nothing.
Definition at line 105 of file queue.h.
Referenced by sd_card::transmit_now().
template<class qType , class qIndexType , qIndexType qSize> qType queue< qType, qIndexType, qSize >::get (void)
This method returns the oldest item in the queue. If the queue was empty, this is already-retreived data. Somebody should have checked if there was new data available using the is_empty() method.
Returns
The data which is pulled out from the queue at the current location
Definition at line 177 of file queue.h.
template<class qType, class qIndexType, qIndexType qSize> qType* queue< qType, qIndexType, qSize >::get_p_buffer (void) inline
This method returns a pointer to the buffer which holds the data in the queue. Normally it's not used, but in some cases (particularly queues of characters) one may need to access the data buffer directly.
Returns
A pointer to the buffer holding the data in the queue
Definition at line 77 of file queue.h.
Referenced by sd_card::sd_card().
template<class qType , class qIndexType , qIndexType qSize> bool queue< qType, qIndexType, qSize >::is_empty (void)
This method returns true if the queue is empty. Empty means that there isn't any data which hasn't previously been read.
Returns
True if the queue has unread data, false if it doesn't
Definition at line 201 of file queue.h.
template<class qType, class qIndexType , qIndexType qSize> bool queue< qType, qIndexType, qSize >::jam (qType data)
This method jams an item into the queue whether the queue is empty or not. This can overwrite existing data, so it must be used with caution.
Parameters
data The data to be jammed into the queue
Returns
True if some data was lost, false otherwise
Definition at line 146 of file queue.h.
template<class qType, class qIndexType, qIndexType qSize> qIndexType queue< qType, qIndexType, qSize >::num_items (void) inline
This method returns the number of items in the queue
Definition at line 70 of file queue.h.
Referenced by sd_card::close_file(), sd_card::putchar(), and sd_card::transmit_now().
template<class qType , class qIndexType, qIndexType qSize> qType queue< qType, qIndexType, qSize >::operator[] (qIndexType index)
This overloaded array subscript operator implements subscripts in the queue. The index is defined relative to the location at which the oldest data in the queue was written. This operator returns the (index)-th item in the queue, or (-1) typecast to the queue data type if there aren't enough items in the queue to get to the given index. The retreived data is not removed from the queue.
Parameters
index The array index into the queue at which to get a data item
Returns
The data which is at the given index
Definition at line 218 of file queue.h.
template<class qType, class qIndexType , qIndexType qSize> bool queue< qType, qIndexType, qSize >::put (qType data)
This method adds an item into the queue. If the buffer is full then nothing is written and true (meaning buffer is full) is returned. This allows the calling program to see that the data couldn't be written and try again if appropriate.
Parameters
data The data to be written into the queue
Returns
True if the buffer was full and data was not written, false otherwise
Definition at line 122 of file queue.h.
Referenced by sd_card::putchar().
The documentation for this class was generated from the following file:
queue.h