Polar Plotter Project: da_motor Class Reference
da_motor Class Reference
#include <da_motor.h>
Public Member Functions
da_motor (base_text_serial *)
void set_mode (uint8_t, uint8_t)
void increase_duty_cycle (uint8_t, uint8_t *)
void decrease_duty_cycle (uint8_t, uint8_t *)
void update_duty_cycle (uint8_t, uint8_t)
Protected Attributes
base_text_serial * ptr_to_serial
Detailed Description
da_motor.cpp is an object class that contains a constructor and three methods which control a motor(s). The constructor initializes timers, prescalars and configures necessary i/o ports. Two of the three methods are mirror images of each other and are used to increase/decrease rotational speed. The final method sets the H bridge to achieve proper rotational direction and braking.
Definition at line 26 of file da_motor.h.
Constructor & Destructor Documentation
da_motor::da_motor (base_text_serial * p_serial_port)
This constructor configures the PWM timer on the ATmega128 and the H-bridges on the VNH motor driver chips set up a motor driver.
Parameters
p_serial_port A pointer to the serial port which writes debugging info.
Definition at line 22 of file da_motor.cpp.
Member Function Documentation
void da_motor::decrease_duty_cycle (uint8_t motor_num, uint8_t * duty_cycle)
manually decrease the duty cycle by 2% da_motor.decrease_duty_cycle allows a user to decrease the rotational speed of a motor. The motor who's speed is adjusted is whichever motor (1 or 2) was previously selected.
Parameters
motor_num,: determines which motor is adjusted
duty_cycle,: a pointer to duty_cycle allows this method to alter values in duty cycle (a variable in main)
Definition at line 164 of file da_motor.cpp.
void da_motor::increase_duty_cycle (uint8_t motor_num, uint8_t * duty_cycle)
manually increase the duty cycle by 2% da_motor.increase_duty_cycle allows a user to increase the rotational speed of a motor. The motor who's speed is adjusted is whichever motor (1 or 2) was previously selected.
Parameters
motor_num,: determines which motor is adjusted
duty_cycle,: a pointer to duty_cycle allows this method to alter values in duty cycle (a variable in main)
Definition at line 131 of file da_motor.cpp.
void da_motor::set_mode (uint8_t motor_num, uint8_t mode)
da_motor.set_mode allows a user to choose a motor's rotational direction or apply unmodulated braking. These tasks are performed by passing motor_num a 1 or a 2 to select which motor's state to change and mode a 1, 2, or 3.
Parameters
motor_num,: selects motor number 1 or 2.
mode,: mode 1 = spin CW mode 2 = spin CCW mode 3 = unmodulated braking.
Definition at line 76 of file da_motor.cpp.
Referenced by Go_Home::run(), and task_PID::run().
void da_motor::update_duty_cycle (uint8_t motor_num, uint8_t duty_cycle)
update_duty_cycle is a method which allows you to update the a motor's duty cycle with any 8-bit value you want instead of incrementally.
Definition at line 191 of file da_motor.cpp.
Referenced by Go_Home::run(), and task_PID::run().
The documentation for this class was generated from the following files:
da_motor.h
da_motor.cpp