Polar Plotter Project: stl_timer.cpp File Reference
stl_timer.cpp File Reference
#include <stdlib.h>
#include <string.h>
#include <avr/interrupt.h>
#include "base_text_serial.h"
#include "stl_timer.h"
Functions
base_text_serial & operator<< (base_text_serial &serial, time_stamp &stamp)
base_text_serial & operator<< (base_text_serial &serial, task_timer &tmr)
ISR (TMR_intr_vect)
Variables
uint16_t ust_overflows = 0
Detailed Description
This file contains a class which runs a task timer whose resolution is one microsecond. The timer is used to help schedule the execution of tasks' run() functions. The functions can be run from a main loop by checking periodically if a task time has expired, or they can be called directly from the timer interrupt service routine in this file, or they can be called from some other hardware interrupt service routine; in the last case this file isn't involved.
Revisions:
08-07-2007 JRR Created this file as daytimer.* with 1 second interrupts
08-08-2007 JRR Added event triggers
12-23-2007 JRR Made more general by allowing faster interrupt rates
01-05-2008 JRR Converted from time-of-day version to microsecond version
03-27-2008 JRR Added operators + and - for time stamps
03-31-2008 JRR Merged in stl_us_timer (int, long) and set_time (int, long)
05-15-2008 JRR Changed to use Timer 3 so Timer 1 can run motor PWM's
05-31-2008 JRR Changed time calculations to use CPU_FREQ_MHz from Makefile
01-04-2009 JRR Now uses CPU_FREQ_Hz (rather than MHz) for better precision
11-24-2009 JRR Changed CPU_FREQ_Hz to F_CPU to match AVR-LibC's name
License: This file copyright 2007 by JR Ridgely. It is released under the Lesser GNU public license, version 2.
Definition in file stl_timer.cpp.
Function Documentation
ISR (TMR_intr_vect)
This is the interrupt service routine which is called whenever there is a compare match on the 16-bit timer's counter. Nearly all AVR processors have a 16-bit timer called Timer 1, and this is the one we use here.
Definition at line 457 of file stl_timer.cpp.
References ust_overflows.
base_text_serial& operator<< (base_text_serial & serial, time_stamp & stamp)
This overloaded operator allows a time stamp to be printed on a serial device such as a regular serial port or radio module in text mode. This allows lines to be set up in the style of 'cout.' The timestamp is always printed as a decimal number.
Parameters
serial A reference to the serial-type object to which to print
stamp A reference to the time stamp to be displayed
Definition at line 413 of file stl_timer.cpp.
References time_stamp::get_microsec(), time_stamp::get_seconds(), and base_text_serial::putchar().
base_text_serial& operator<< (base_text_serial & serial, task_timer & tmr)
This overloaded operator allows the task timer to print the current time on a serial device such as a regular serial port or radio module in text mode. This allows lines to be set up in the style of 'cout.' The printing is done by the time_stamp class; this method just calls the timer's get_time_now() method to get a time stamp, then has the time stamp print itself.
Parameters
serial A reference to the serial-type object to which to print
tmr A reference to the timer whose time is to be displayed
Definition at line 444 of file stl_timer.cpp.
References task_timer::get_time_now().
Variable Documentation
uint16_t ust_overflows = 0
This variable holds the number of times the hardware timer has overflowed. This number is equivalent to the upper 16 bits of a 32-bit timer, and is so used.
Definition at line 44 of file stl_timer.cpp.
Referenced by task_timer::get_time_now(), ISR(), task_timer::save_time_stamp(), and task_timer::set_time().