Polar Plotter Project: stl_timer.h File Reference
stl_timer.h File Reference
Classes
union time_data_32
class time_stamp
class task_timer
Macros
#define TMR_TCNT_REG TCNT1
These defines prevent this file from being included more than once in a *.cc file.
#define TMR_intr_vect TIMER1_OVF_vect
The timer overflow interrupt vector.
Functions
base_text_serial & operator<< (base_text_serial &, time_stamp &)
base_text_serial & operator<< (base_text_serial &, task_timer &)
Detailed Description
This file contains a class which runs a task timer whose resolution is one microsecond. The timer is used to help schedule the execution of tasks' run() methods, and it is also used to keep track of real time in general. The run() methods can be run from a main loop by checking periodically if a task time has expired, or they can be called directly from a timer interrupt service routine.
Revisions:
08-07-2007 JRR Created this file as daytimer.* with 1 second interrupts
08-08-2007 JRR Added event triggers
12-23-2007 JRR Made more general by allowing faster interrupt rates
01-05-2008 JRR Converted from time-of-day version to microsecond version
03-27-2008 JRR Added operators + and - for time stamps
03-31-2008 JRR Merged in stl_us_timer (int, long) and set_time (int, long)
05-15-2008 JRR Changed to use Timer 3 so Timer 1 can run motor PWM's
05-31-2008 JRR Changed time calculations to use CPU_FREQ_MHz from Makefile
01-04-2009 JRR Now uses CPU_FREQ_Hz (rather than MHz) for better precision
11-24-2009 JRR Changed CPU_FREQ_Hz to F_CPU to match AVR-LibC's name
License: This file copyright 2007 by JR Ridgely. It is released under the Lesser GNU public license, version 2.
Definition in file stl_timer.h.
Macro Definition Documentation
#define TMR_TCNT_REG TCNT1
These defines prevent this file from being included more than once in a *.cc file.
Register that holds the time count
Definition at line 44 of file stl_timer.h.
Referenced by task_timer::get_time_now(), task_timer::save_time_stamp(), and task_timer::set_time().
Function Documentation
base_text_serial& operator<< (base_text_serial & serial, time_stamp & stamp)
This overloaded operator allows a time stamp to be printed on a serial device such as a regular serial port or radio module in text mode. This allows lines to be set up in the style of 'cout.' The timestamp is always printed as a decimal number.
Parameters
serial A reference to the serial-type object to which to print
stamp A reference to the time stamp to be displayed
Definition at line 413 of file stl_timer.cpp.
References time_stamp::get_microsec(), time_stamp::get_seconds(), and base_text_serial::putchar().
base_text_serial& operator<< (base_text_serial & serial, task_timer & tmr)
This overloaded operator allows the task timer to print the current time on a serial device such as a regular serial port or radio module in text mode. This allows lines to be set up in the style of 'cout.' The printing is done by the time_stamp class; this method just calls the timer's get_time_now() method to get a time stamp, then has the time stamp print itself.
Parameters
serial A reference to the serial-type object to which to print
tmr A reference to the timer whose time is to be displayed
Definition at line 444 of file stl_timer.cpp.
References task_timer::get_time_now().